### ISSUE TITLE
itemOpenChanged getting error

### ISSUE THREAD

**Issue by tylerthehaas** [Hackception/hc-tree-view#21]
when itemOpenChanged is called I get an uncaught TypeError: Cannot read property 'root' of undefined.  I also saw these errors in the performance tests.

**Comment by admwx7** [comment]
I need more details on how to recreate the issue, what did you click on?  What does the items data look like?  Are you calling any functions on the element?

It would be best to create a JSFiddle that recreates the issue for me so I can debug it.

**Comment by tylerthehaas** [comment]
You should be able to go into the ms/API branch of mtz-group-manager to recreate this issue.

I also believe that there may be a larger issue with this function because as I am working the feature enhancement to allow the tree to be collapsed programmatically I fired the `item-open-changed` event and it seems to run fine when I step through the code but it doesn't collapse the tree in the same way as when you click on it.
