### ISSUE TITLE
[REQ] Allow Selected nodes to stay open

### ISSUE THREAD

**Issue by stramel** [Hackception/hc-tree-view#22]
Request has been made to allow selected nodes to stay open instead of collapsing when entering a different branch.

**Comment by admwx7** [comment]
There's currently a limitation with iron-list that once you hit ~2500 nodes visible on the screen scrolling starts getting a rather noticeable delay due to how it parses through items, collapsing the unused sections of the tree is a way to combat this getting out of hand too quick.
