### ISSUE TITLE
nested-list demo crashing Chrome

### ISSUE THREAD

**Issue by goatandsheep** [Hackception/hc-tree-view#50]
Going to the nested-list demo is crashing chrome. Are you noticing the same behaviour? If not, I'll give you the error.

**Comment by stramel** [comment]
Hmm, it is locking up in `hc-nested-list`. Can you provide the error you are seeing? 

We are going to take a look into it. The `hc-tree-view` doesn't seem to be locking up.

**Comment by goatandsheep** [comment]
Re-tested it and not seeing any errors in the console to display, but it freezes up the entire tab. Is nested-list the same as tree-view without the checkboxes?

**Comment by goatandsheep** [comment]
Both nested-list and nested-list-item are freezing the tab

**Comment by admwx7** [comment]
My bad, fixed that in my hybridization branch (#51) @goatandsheep turns out trying to generate a list of 100^3 items isn't quite ready yet with all of the additional logic I've added over time, I'll bring it back to that level once I've wrapped up my other performance issues.

**Comment by goatandsheep** [comment]
@admwx7 thanks! keep me updated
